<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.49.0.2111" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1560" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Plugin.FilePicker" Version="2.1.41" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Mono.Android">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="EditLangPage.xaml.cs">
      <DependentUpon>EditLangPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="SettingsPageDetail.xaml.cs">
      <DependentUpon>SettingsPageDetail.xaml</DependentUpon>
    </Compile>
    <Compile Update="VocablePageDetail.xaml.cs">
      <DependentUpon>VocablePageDetail.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="EditVocablePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="EditLangPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="TrainingPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="TrainingPageDetail.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="TrainingPageMaster.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="EditVocablePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="TrainingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="TrainingPageDetail.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="TrainingPageMaster.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
</Project>